version: "3"
services:
    neo4j:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=none