sudo: required
services:
    - docker

before_install:
    - docker build -t alo42/api-test -f Dockerfile.dev .

scripts:
    - docker run -e CI=true alo42/api-test npm test

after_successes:
    - docker build -t alo42/localhost-api .
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
    - docker push alo42/localhost-api