version: "3"
services:
  api:
      depends_on:
        - "neo4j1"
        - "neo4j2"
      build:
        dockerfile: Dockerfile.dev
        context: ./api
      volumes:
        - /app/node_modules
        - ./api:/app
  neo4j1:
    image: alo42/neo4j
    ports:
      - "7475:7474"
      - "7688:7687"
    environment:
      - NEO4J_AUTH=none
  neo4j2:
    image: alo42/neo4j
    ports:
      - "7476:7474"
      - "7689:7687"
    environment:
      - NEO4J_AUTH=none
  