version: "3"
services:
    nginx:
        restart: always
        container_name: nginx
        depends_on:
            - "api"
            - "neo4j"
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '80:80'
    neo4j:
        container_name: neo4j
        build:
            dockerfile: Dockerfile
            context: ./neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_AUTH=none
    api:
        container_name: api
        depends_on:
            - "neo4j"
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - /app/node_modules
            - ./api:/app
        env_file:
            - api/.env.docker
    account:
        container_name: account
        depends_on:
            - "neo4j"
        build:
            dockerfile: Dockerfile.dev
            context: ./account-services
        volumes:
            - /app/node_modules
            - ./account-services:/app
        env_file:
            - account-services/.env.docker
    media:
        container_name: media
        depends_on:
            - "neo4j"
        build:
            dockerfile: Dockerfile.dev
            context: ./media-services
        volumes:
            - ./media-services:/app
        env_file:
            - media-services/.env.docker
        ports:
            - "3001:3001"
