version: "3"
services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /app/node_modules
            - ./:/app
        ports:
            - '4000:4000'