version: "3"
services:
    neo4j:
        image: alo42/neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_AUTH=none
    api:
        image: alo42/localhost-api
        depends_on:
            - "neo4j"
        env_file:
            - ./api/.env.docker
    nginx:
        image: alo42/localhost-nginx
        restart: always
        depends_on:
            - "api"
            - "neo4j"
        ports:
            - '80:80'