version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localhost-api-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qlv7hz4hlntv"
s3_prefix = "localhost-api-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
