/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:273181460905",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_BPMkByGn0",
    "aws_user_pools_web_client_id": "5adekti85le21vpe7guuu066sf",
    "oauth": {}
};


export default awsmobile;
