apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: NEO4J_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: NEO4J_PASSWORD
              name: env-docker
        - name: NEO4J_URI
          valueFrom:
            configMapKeyRef:
              key: NEO4J_URI
              name: env-docker
        - name: NEO4J_USER
          valueFrom:
            configMapKeyRef:
              key: NEO4J_USER
              name: env-docker
        image: alo42/localhost-api
        imagePullPolicy: ""
        name: api
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
